### ISSUE TITLE
Add default npm versions

### ISSUE THREAD

**Issue by Maxim-Mazurok** [ehmicky/all-node-versions#8]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

I'm writing a script that would use listr and nodeenv to install deps and run tests for all projects recursively, it detects required node and npm versions from package.json engines section, and to optimize it I need to know if I node version I'm installing is shipped with npm version that I need by default, or if I need to pass `--npm=... --with-npm` to nodeenv.

### Describe the solution you'd like

Something like `[{node: "16.3.0", npm: "7.15.1"}, ...]`

### Pull request (optional)

- [x] I can submit a pull request.

**Comment by ehmicky** [comment]
That's a great idea! Thanks for suggesting it.

@all-contributors please ad @Maxim-Mazurok for code, test, ideas, doc

**Comment by ehmicky** [comment]
That's a great idea! Thanks for suggesting it.

@all-contributors please add @Maxim-Mazurok for code, test, ideas, doc

**Comment by ehmicky** [comment]
Released in [`11.0.0`](https://github.com/ehmicky/all-node-versions/releases/tag/11.0.0).
